#!/usr/bin/env bash

# Simple script to compile a view latex documents

# Function compiles first before use

latex_pdf_mkdir{

	if [-d "latex_pdf"]
	then
		echo "Directory Exists"
	else
		echo "Creating directory..."
		mkdir latex_pdf
	fi
}


# Takes latex file as input
LATEX=${1?Error: Please choose a latex file}
externalprogram "$LATEX"

# source: https://stackoverflow.com/questions/965053/extract-filename-and-extension-in-bash 

FILENAME="${LATEX%.*}"

# TODO: Scan the current directory for a latex_pdf dir, if none exists then make one
# and move the .pdf with the associated filename to that directory
# add an option "-o", so the user doesn't open the file automatically, otherwise the pdf is opened using evince

EXTENSION="${LATEX##*.}"

PDF=/usr/bin/pdflatex $LATEX

latex_pdf_mkdir

echo "Compiling..."



$PDF.pdf
